### ISSUE TITLE
Higher Order Curves

### ISSUE THREAD

**Issue by LucasHimself** [be-fonts/boring-expansion-spec#2] opened 2021-06-24 21:34 UTC
_Expansion thoughts designers perspective_

I love the idea to ditch the CFF and CFF2 tables and put all outlines in glyf.
It means having lineto, quadraticsto and cubiccurveto available, thus allowing me to combine 2nd and 3rd degree segments in one outline. I expressed this wish with explanations in a PS<>TT battle some years ago, [that lecture is still online](https://www.youtube.com/watch?v=I75Efo7whrs)

However I would also really really would like to be able to expand that with fourthdegreecurveto and fitfthdegreecurveto.
Why? 
I want to be compatible with product designers and be able to achieve the same curve continuity as products have.
I make a lot of logo-fonts in which outlines need to have a much higher quality than what is possible now, because such logos will be cut in gigantic sizes and live long and prosperous in front of buildings.
I want to be able to draw for instance the outline of an iPhone in a variable font. It is impossible. The connections from curves to straight sides are smooth with a nice increasing curve speed, and it was designed with a 5th degree curve. With 2nd and 3rd degree curves, I can only make rough approximations of such curves, and I need to insert extra points near the connection, that will not interpolate well, it is a total design disaster.

Yes, 5th degree curves need more time to calculate, but I would only use them where really necessary, and at the same time I would replace cubics with quadratics wherever possible and save calculation time.
Adobe has dictated the 3rd degree Bezier for the graphic world, but for drawing beautiful shapes, they really suck.
If a carpenter uses a machine to cut wood from 3rd degree curves, she/he will feel with the fingers that the connections aren’t right, and use sanding paper until it feels good. 

5th degree Bezier curves allow feel-good curves in fonts and machines.

**Comment by ldo** [comment] 2021-06-26 07:40
What about NURBS curves instead of Béziers?

**Comment by LucasHimself** [comment] 2021-06-30 08:20
@ldo I see no arguments for NURBS to discuss, what about them? Aren't they collections of Beziers used only in the VFX industry?

**Comment by ldo** [comment] 2021-06-30 08:59
Their 3D equivalent, NURBS patches, are commonly used in applications like automotive design, where accuracy of shapes is important. So it makes sense to consider them for 2D use. They give you more control points without actually requiring higher-order polynomials.

We are recommended to avoid higher-order Béziers because they become difficult to control; every control point influences the entire curve, in ways that are hard to intuit.

**Comment by ldo** [comment] 2021-07-06 05:48
I should also point out that the specific issue you mention with the smoothness (or not) of the transition between curve segments is orthogonal to the question of what kind (or order) of spline curves to use. It is because the join only has <I>C<SUP>1</SUP></I> continuity. This means that the direction of the curve changes smoothly across the join, but its radius of curvature does not.

For example, railway engineers are familiar with this; imagine you are a passenger on a train passing by such a join in the shape of the track: at all but the slowest speeds, you will likely notice a sudden lurching change in lateral acceleration, caused by the step-change in centripetal force associated with the change in radius of curvature. This kind of thing can bring on motion sickness.

The solution is to require <I>C<SUP>2</SUP></I> continuity across the join, so the radius of curvature changes smoothly, not just the curve direction.

**Comment by behdad** [comment] 2021-09-16 17:59
Thinking more, this is out of scope, since I really want to ship Boring Expansion within the rest of the year, and I don't see this happening. Will be in scope for next-gen font formats.

**Closed by behdad** 2021-09-16 17:59 UTC
Labels: maybe later
